sudo: required
services:
  - docker
before_install:
  - docker build  -t  ghorfi/react-test -f  ./client/Dockerfile.dev ./client
script:
  - docker run ghorfi/react-test  npm test  --  --coverage
after_success:
  - docker build -t ghorfi/multi-client ./client
  - docker build -t ghorfi/multi-nginx ./nginx
  - docker build -t ghorfi/multi-server ./server
  - docker build -t ghorfi/multi-worker ./worker
  - echo  "$DOCKER_PASSWORD" |  docker  login -u  "$DOCKER_ID"  --password-stdin
  - docker  push  ghorfi/multi-client
  - docker  push  ghorfi/multi-nginx
  - docker  push  ghorfi/multi-server
  - docker  push  ghorfi/multi-worker
