sudo: required
services:
  - docker
before_install:
  - docker build  -t  hassanighorfi/react-test -f  ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true hassanighorfi/react-test  npm test  --  --coverage
after_success:
  - docker build -t hassanighorfi/multi-client ./client
  - docker build -t hassanighorfi/multi-nginx ./nginx
  - docker build -t hassanighorfi/multi-server ./server
  - docker build -t hassanighorfi/multi-worker ./worker
  - echo  "$DOCKER_PASSWORD" |  docker  login -u  "$DOCKER_ID"  --password-stdin
  - docker  push  hassanighorfi/multi-client
  - docker  push  hassanighorfi/multi-nginx
  - docker  push  hassanighorfi/multi-server
  - docker  push  hassanighorfi/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app:  multi-docker
  env:  MultiDocker-env
  bucket_name:  elasticbeanstalk-us-east-2-024843734905
  bucket_path:  docker-multi
  on:
    branch: master
  access_key_id:  $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
